version: "3.9"
services:

    gateway:
        build:
            context: docker
            dockerfile: development/gateway/Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - nginx
        networks:
            - app-network

    nginx:
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - .:/app
        depends_on:
            - php-fpm
        networks:
            - app-network

    php-fpm:
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            PHP_IDE_CONFIG: serverName=API
            SENTRY_DSN: ${SENTRY_DSN}
            DB_DRIVER: ${DB_DRIVER}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_CHARSET: ${DB_CHARSET}
        volumes:
            - .:/app
        networks:
            - app-network

    php-cli:
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            SENTRY_DSN: ${SENTRY_DSN}
            DB_DRIVER: ${DB_DRIVER}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            DB_CHARSET: ${DB_CHARSET}
        volumes:
            - .:/app
        networks:
            - app-network

    db:
        image: mariadb
        ports:
            - "8887:3306"
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_DATABASE: app
        volumes:
            - app-mariadb:/var/lib/mysql/data
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=500M
        ports:
            - "8888:80"
        networks:
            - app-network

volumes:
    app-mariadb:

networks:
    app-network:
        driver: bridge
